FROM golang:1.12.9

ARG GOPATH
#ARG OUTPUT_DIR
#ARG ROOTDIR

ENV GOPATH=/go

# Recompile everything and create a static binary
#ENV CGO_ENABLED=0
#CMD go build -v -a --installsuffix cgo -ldflags '-s' -o /host/porter

ADD . /go/src/github.com/gloo

#RUN mkdir /go/bin

RUN apt-get update

RUN apt-get install -y \
      bash \
      curl \
      sudo \
      make \
      git \
      vim \
      docker \
    && rm -rf /var/cache/apk/* \
    && cd $GOPATH/src/github.com/gloo

ENV GOPATH=$GOPATH

RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/gloo

RUN /go/bin/dep ensure -v

# ginkgo
RUN go get github.com/onsi/ginkgo/ginkgo

# Set the Kubernetes version as found in the UCP Dashboard or API
ENV k8sversion=v1.14.1

# Get the kubectl binary.
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$k8sversion/bin/linux/amd64/kubectl

# Make the kubectl binary executable.
RUN chmod +x ./kubectl

ENV PATH=/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:$PATH

# Move the kubectl executable to /usr/local/bin.
RUN sudo mv ./kubectl /usr/local/bin/kubectl

# CMD /bin/bash
