FROM golang:1.12.9 AS build

ARG GOPATH

ENV GOPATH=/go

ADD . /go/src/github.com/gloo

RUN apt-get update

RUN apt-get install -y \
      bash \
      curl \
      make \
      git \
      docker \
    && rm -rf /var/cache/apk/* \
    && cd $GOPATH/src/github.com/gloo

ENV GOPATH=$GOPATH

RUN go get -u github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/gloo

RUN /go/bin/dep ensure -v

RUN make gateway

FROM scratch AS final

ENV PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PATH

COPY --from=build /go/src/github.com/gloo/_output/gateway /bin/gateway
COPY --from=build /bin/bash /bin/bash

ENTRYPOINT ["/bin/gateway"]
CMD []
